# Setup

In [188]:
import pandas as pd
import numpy as np

# Set a random seed so everyone gets the same dataset
np.random.seed(42)

data = {
    "patient_id": [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 103, 107, 122, 123
    ],
    "animal_type": [
        "dog", "cat", "dog", "rabbit", "cat",
        "dog", "cat", "bird", "dog", "cat",
        "dog", "rabbit", "cat", "dog", "bird",
        "cat", "dog", "cat", "dog", "rabbit",
        "cat", None, "cat", "dog", "bird"
    ],
    "age_years": [
        3, 7, 2, 4, 1,
        5, 8, 2, 6, 3,
        None, 1, 4, 9, 3,
        2, 7, None, 4, 2,
        6, 2, 8, None, 1
    ],
    "weight_kg": [
        18.2, 4.1, 22.5, 1.8, 3.9,
        31.0, 4.7, 0.09, 14.3, 5.2,
        27.8, 2.1, 999.0, 10.5, 0.11,
        3.8, 24.1, 4.4, -5.0, 1.9,
        5.1, 22.5, 4.7, 16.3, 0.08
    ],
    "visit_reason": [
        "checkup", "checkup", "vaccination", "checkup", "dental",
        "injury", "checkup", "checkup", "dental", "vaccination",
        "checkup", "dental", "injury", "checkup", "vaccination",
        "injury", "vaccination", "checkup", "dental", "checkup",
        "vaccination", "vaccination", "checkup", "injury", "checkup"
    ],
    "visit_cost_usd": [
        85.0, 70.0, None, 65.0, 120.0,
        None, 75.0, 60.0, 130.0, 70.0,
        80.0, 115.0, 90.0, 85.0, 60.0,
        None, 95.0, 70.0, 125.0, 65.0,
        70.0, None, 75.0, 90.0, 60.0
    ],
    "follow_up_needed": [
        False, False, True, False, True,
        True, False, False, True, False,
        False, True, True, False, False,
        True, False, False, True, False,
        False, True, False, True, False
    ]
}

clinic = pd.DataFrame(data)
print("Dataset created. Shape:", clinic.shape)
clinic.head()

Dataset created. Shape: (25, 7)

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.2,checkup,85.0,False
1,102,cat,7.0,4.1,checkup,70.0,False
2,103,dog,2.0,22.5,vaccination,NaN,True
3,104,rabbit,4.0,1.8,checkup,65.0,False
4,105,cat,1.0,3.9,dental,120.0,True

In [189]:
start_rows = 25
start_nulls = 8   # from your Task 2 total
start_duplicates = 2  # from your Task 7 count

# Task 1

## Part 1

In [190]:
clinic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        25 non-null     int64
 1   animal_type       24 non-null     object
 2   age_years         22 non-null     float64
 3   weight_kg         25 non-null     float64
 4   visit_reason      25 non-null     object
 5   visit_cost_usd    21 non-null     float64
 6   follow_up_needed  25 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.3+ KB

### Part 1 Questions:

1. 25 rows, 7 columns
2. Columns with missing values: animal_type, age_years, visit_cost_usd
3. `follow_up_needed` is type Boolean

## Part 2

In [191]:
clinic.describe()

       patient_id  age_years   weight_kg  visit_cost_usd
count   25.000000  22.000000   25.000000       21.000000
mean   111.440000   4.090909   48.927200       83.571429
std      6.801225   2.524340  198.178411       21.974011
min    101.000000   1.000000   -5.000000       60.000000
25%    106.000000   2.000000    2.100000       70.000000
50%    111.000000   3.500000    4.700000       75.000000
75%    117.000000   6.000000   18.200000       90.000000
max    123.000000   9.000000  999.000000      130.000000

### Part 2 Questions:

1. min weight: -5kg. This is not possible. (Unless antimatter is real)
2. Max weight: 999kg. Not likely unless this is an exotic vet dealing with an elephant.

## Part 3

In [192]:
clinic['visit_reason'].value_counts()

visit_reason
checkup        11
vaccination     6
dental          4
injury          4
Name: count, dtype: int64

### Part 3 Question:
1. The most common reason for visits is checkup.

# Task 2

In [193]:
clinic.isna()

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False
17,False,False,True,False,False,False,False
18,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False
21,False,True,False,False,False,True,False
22,False,False,False,False,False,False,False
23,False,False,True,False,False,False,False
24,False,False,False,False,False,False,False

In [194]:
clinic.isna().sum()
# age_years and visit_cost_usd have the most missing values

patient_id          0
animal_type         1
age_years           3
weight_kg           0
visit_reason        0
visit_cost_usd      4
follow_up_needed    0
dtype: int64

# Task 3

In [195]:
clinic = clinic.dropna(subset=["animal_type"])
clinic.shape
#24 rows are left

(24, 7)

# Task 4

In [196]:
median_age = clinic["age_years"].median()
print(median_age)

4.0

In [197]:
clinic["age_years"] = clinic["age_years"].fillna(median_age)

In [198]:
clinic["age_years"].isna().sum()

np.int64(0)

# Task 5

In [199]:
clinic.groupby("visit_reason")["visit_cost_usd"].transform('median')

0      70.0
1      70.0
2      70.0
3      70.0
4     122.5
5      90.0
6      70.0
7      70.0
8     122.5
9      70.0
10     70.0
11    122.5
12     90.0
13     70.0
14     70.0
15     90.0
16     70.0
17     70.0
18    122.5
19     70.0
20     70.0
22     70.0
23     90.0
24     70.0
Name: visit_cost_usd, dtype: float64

In [200]:
clinic["visit_cost_usd"] = clinic["visit_cost_usd"].fillna(
    clinic.groupby("visit_reason")["visit_cost_usd"]
    .transform("median")
)

In [201]:
clinic['visit_cost_usd'].isna().sum()

np.int64(0)

### Task 5 Question:
group-based filling is more accurate because within each category, the cost will likely be much more similar. Between categories, cost can vary more. So grouping by reason for visit allows for a more accurate estimate of the missing costs.

# Task 6

In [202]:
clinic[clinic['weight_kg'] <= 0 ]

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
18,119,dog,4.0,-5.0,dental,125.0,True

In [203]:
clinic[clinic['weight_kg'] > 200]
# chOnky cat

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
12,113,cat,4.0,999.0,injury,90.0,True

In [204]:
clinic.loc[clinic['weight_kg'] <= 0, 'weight_kg'] = np.nan
clinic.loc[clinic['weight_kg'] > 200, 'weight_kg'] = np.nan
clinic["weight_kg"].isna().sum()
# Count of null values in weight column is now 2

np.int64(2)

# Task 7

In [205]:
clinic[clinic.duplicated()]
# one duplicate was found
clinic = clinic.drop_duplicates()
clinic.shape

(23, 7)

# Task 8

In [206]:
clinic.info()
#down 2 rows, non-null count changed

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        23 non-null     int64
 1   animal_type       23 non-null     object
 2   age_years         23 non-null     float64
 3   weight_kg         21 non-null     float64
 4   visit_reason      23 non-null     object
 5   visit_cost_usd    23 non-null     float64
 6   follow_up_needed  23 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.3+ KB

### From Task1 ###
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   patient_id        25 non-null     int64  
 1   animal_type       24 non-null     object 
 2   age_years         22 non-null     float64
 3   weight_kg         25 non-null     float64
 4   visit_reason      25 non-null     object 
 5   visit_cost_usd    21 non-null     float64
 6   follow_up_needed  25 non-null     bool   
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.3+ KB

In [207]:
clinic.isna().sum()
#2 remaining null values

patient_id          0
animal_type         0
age_years           0
weight_kg           2
visit_reason        0
visit_cost_usd      0
follow_up_needed    0
dtype: int64

In [208]:
clinic.describe()
#min and max values look better now

       patient_id  age_years  weight_kg  visit_cost_usd
count    23.00000  23.000000  21.000000       23.000000
mean    112.00000   4.000000   9.618095       83.913043
std       6.78233   2.276361   9.854323       21.157232
min     101.00000   1.000000   0.080000       60.000000
25%     106.50000   2.000000   2.100000       70.000000
50%     112.00000   4.000000   4.700000       80.000000
75%     117.50000   5.500000  16.300000       90.000000
max     123.00000   9.000000  31.000000      130.000000

In [209]:
clinic.duplicated().sum()
#result is zero

np.int64(0)

# Task 8 discussion questions
1. animal type is much more ambiguous than taking a median age for animals that typically don't live more than a few decades.
2. The median would have taken the median over all the different visit reasons making the data skewed towards less focused areas. Grouping took the median in each category for each service.
3. The other data is still usable and adds value. Deleting the rows would take away from our sample size in other columns.

# Task 9

In [210]:
clinic['weight_kg'].describe()
clinic.shape

(23, 7)

In [211]:
clinic['weight_kg'] = clinic['weight_kg'].clip(lower=0.05, upper=80)
clinic['weight_kg'].describe()
clinic.shape

(23, 7)

Clip is more appropriate if you are only slightly modifying values. Doing so allows you to keep usable numbers for the sake of calculations later on.

# Task 10

In [212]:
clinic = clinic.dropna(subset=['weight_kg'])
clinic.info()
# Rows: 21

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        21 non-null     int64
 1   animal_type       21 non-null     object
 2   age_years         21 non-null     float64
 3   weight_kg         21 non-null     float64
 4   visit_reason      21 non-null     object
 5   visit_cost_usd    21 non-null     float64
 6   follow_up_needed  21 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.2+ KB

# Task 11

In [213]:
print(clinic)
clinic[clinic.duplicated(subset=['patient_id'], keep=False)]

# No rows share patient ID because we removed duplicates earlier and
# dropped the duplicate of 103 because it did not record animal_type

    patient_id animal_type  age_years  weight_kg visit_reason  visit_cost_usd  \
0          101         dog        3.0      18.20      checkup            85.0
1          102         cat        7.0       4.10      checkup            70.0
2          103         dog        2.0      22.50  vaccination            70.0
3          104      rabbit        4.0       1.80      checkup            65.0
4          105         cat        1.0       3.90       dental           120.0
5          106         dog        5.0      31.00       injury            90.0
6          107         cat        8.0       4.70      checkup            75.0
7          108        bird        2.0       0.09      checkup            60.0
8          109         dog        6.0      14.30       dental           130.0
9          110         cat        3.0       5.20  vaccination            70.0
10         111         dog        4.0      27.80      checkup            80.0
11         112      rabbit        1.0       2.10       dental           115.0
13         114         dog        9.0      10.50      checkup            85.0
14         115        bird        3.0       0.11  vaccination            60.0
15         116         cat        2.0       3.80       injury            90.0
16         117         dog        7.0      24.10  vaccination            95.0
17         118         cat        4.0       4.40      checkup            70.0
19         120      rabbit        2.0       1.90      checkup            65.0
20         121         cat        6.0       5.10  vaccination            70.0
23         122         dog        4.0      16.30       injury            90.0
24         123        bird        1.0       0.08      checkup            60.0

    follow_up_needed
0              False
1              False
2               True
3              False
4               True
5               True
6              False
7              False
8               True
9              False
10             False
11              True
13             False
14             False
15              True
16             False
17             False
19             False
20             False
23              True
24             False

Empty DataFrame
Columns: [patient_id, animal_type, age_years, weight_kg, visit_reason, visit_cost_usd, follow_up_needed]
Index: []

We would want to keep the duplicated Patient ID rows **if** they represent different appointments for the same animal. If there was an input error with the duplicate (exact duplicate of the earlier row, or just some other input error) then we would want to drop the duplicate row.

# Task 12

In [215]:
summary = pd.DataFrame({
    "metric": ["row count", "null values", "duplicate rows"],
    "before": [start_rows, start_nulls, start_duplicates],
    "after": [
        clinic.shape[0],
        clinic.isna().sum().sum(),
        clinic.duplicated().sum()
    ]
})
print(summary)
# The after column does match our work

           metric  before  after
0       row count      25     21
1     null values       8      0
2  duplicate rows       2      0